[project]
name = "mcpone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-groq>=0.3.2",
    "langchain-openai>=0.3.23",
    "mcp-use>=1.3.0",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
]
